name: MCHunt
version: '${version}'
main: com.rexchoppers.mchunt.MCHunt
api-version: '1.21'
depend: [
  ProtocolLib,
  LibsDisguises,
  WorldGuard
]
commands:
  mchunt:
    description: Opens the MCHunt GUI
    aliases: [mch]
    usage: /<command>
    permission: mchunt.use
permissions:
  mchunt.use:
    description: Allows using the /mchunt command
    default: true
