FROM debian:buster-slim

RUN apt-get update && apt-get install -y wget

RUN wget https://github.com/Tiiffi/mcrcon/releases/download/v0.7.2/mcrcon-0.7.2-linux-x86-64.tar.gz

RUN tar -xf mcrcon-0.7.2-linux-x86-64.tar.gz

CMD ["sh", "-c", "tail -f /dev/null"]